FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN pnpm install
# Can you add a script to the global package.json that does this?
RUN pnpm run db:generate

# Can you filter the build down to just one app?
RUN pnpm run build

CMD ["pnpm", "run", "start-user-app"]